version: "3.8"

services:
  redis:
    container_name: ats_redis
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 30 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${HOME}/data/ats/redis:/data/redis
